apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vandalizer.fullname" . }}-backend-env
  labels:
    {{- include "vandalizer.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.backendEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
