apiVersion: v1
kind: Service
metadata:
  name: {{ include "vandalizer.fullname" . }}-redis
  labels:
    {{- include "vandalizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    {{- include "vandalizer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
